pipeline {
    agent any
    environment {
        // Pulls username/password from Jenkins credentials
        DOCKER_CREDS = credentials('dockerhub-creds')
        IMAGE_NAME = 'adi1310/demo-spring:latest'
    }
 
    stages {
        stage('Build Spring Boot App') {
            steps {
                // Assuming you use Maven inside your project directory
                sh './mvnw clean package -DskipTests'
            }
        }
        stage('Build & Push Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME} ."
                sh "echo \$DOCKER_CREDS_PSW | docker login -u \$DOCKER_CREDS_USR --password-stdin"
                sh "docker push ${IMAGE_NAME}"
            }
        }
 
        stage('Deploy to AWS EKS') {
            steps {
                // Uses the Kubernetes CLI plugin and your uploaded yaml file
                withKubeConfig([credentialsId: 'eks-kubeconfig']) {
                    // Apply your existing deployment and service configurations
                    sh 'kubectl apply -f deployment.yaml'
                    // Force EKS to restart the pods so they pull your newly pushed 'latest' image
                    sh 'kubectl rollout restart deployment/spring-app-deployment'
                    // Verify the status
                    sh 'kubectl get pods'
                }
            }
        }
    }
}
